version: '3'
services:
  app:
    image: openjdk:17-jdk-slim
    container_name: hydronotis-app
    build:
      context: . 
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=vaadinstart
      - DB_USERNAME=vaadinstart
      - DB_PASSWORD=vaadinstart
    ports:
      - "8080:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
